projects:
  fitnessproject:
    schemaPath: amplify/backend/api/fitnessproject/build/schema.graphql
    includes:
      - functions
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
