name: Project Setup
run-name: Setup Project

env:
  TEST_RUNNER_CI: 1

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
      - development
jobs:
  setup_and_lint:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install npm
        run: npm install -g npm@8.3.2
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run staged-lint

  unit_tests:
    needs: setup_and_lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Run tests
        run: npm run test:ci

  build:
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
      - name: Bundle project
        run: npx expo export
