name: Project Setup
run-name: Setup Project
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14.17.0"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install npm
        run: npm install -g npm@8.3.2
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run staged-lint
      - name: Run tests
        run: npm run test:ci
      - name: Bundle project
        run: npx expo export
