name: Project Build

env:
  TEST_RUNNER_CI: 1
  NODE_VERSION: "20.0.0"
  IOS_CHECK_NAME: Wait for iOS Build
  ANDROID_CHECK_NAME: Wait for Android Build

on:
  pull_request:
    types: [opened, synchronize]
    branches: [master, development]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_platform_changes:
    runs-on: ubuntu-latest
    outputs:
      ios_changes: ${{ steps.check-files.outputs.ios_changes }}
      android_changes: ${{ steps.check-files.outputs.android_changes }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch base branch
        run: git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          
      - name: Install Dependencies
        run: |
          if [ ! -d "node_modules" ]; then
            echo "Cache not found, running npm ci."
            npm ci
          else
            echo "Cache restored, skipping npm ci."
          fi
        env:
          TIFSHARED_JS: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Check for platform-specific changes
        id: check-files
        run: |
          git diff --name-only FETCH_HEAD HEAD > changed_files.txt
          
          # Initialize change flags
          ios_changed=false
          android_changed=false
          
          # iOS native file patterns in project
          if grep -q -E "\.(swift|m|h|mm|plist|xcodeproj|xcworkspace|pbxproj)$|ios/Podfile|ios/Podfile.lock" changed_files.txt; then
            ios_changed=true
          fi
          
          # Android native file patterns in project
          if grep -q -E "\.(kotlin|kt|java|gradle|xml|aar)$|android/gradle|android/build.gradle|android/settings.gradle" changed_files.txt; then
            android_changed=true
          fi
          
          # Install dependencies if package.json changed
          if git diff FETCH_HEAD HEAD -- package.json | grep -q "dependencies\|devDependencies"; then
            echo "Checking package.json changes..."
            
            # Install dependencies for both versions to compare
            git show FETCH_HEAD:package.json > old_package.json
            git show HEAD:package.json > new_package.json
            
            # Create temporary directories for both versions
            mkdir -p old_deps new_deps
            
            # Install old dependencies
            cd old_deps
            cp ../old_package.json package.json
            npm install --production --ignore-scripts
            cd ..
            
            # Install new dependencies
            cd new_deps
            cp ../new_package.json package.json
            npm install --production --ignore-scripts
            cd ..
            
            # Function to check for native code in node_modules
            function check_native_code() {
              local dir=$1
              # Check for native files recursively
              if find "$dir/node_modules" -type f \( \
                -name "*.swift" -o \
                -name "*.m" -o \
                -name "*.h" -o \
                -name "*.mm" -o \
                -name "*.pbxproj" -o \
                -name "*.xcodeproj" -o \
                -name "*.xcworkspace" -o \
                -name "*.plist" -o \
                -name "Podfile" -o \
                -name "*.gradle" -o \
                -name "*.java" -o \
                -name "*.kt" -o \
                -name "*.aar" \
              \) 2>/dev/null | grep -q .; then
                return 0
              fi
              
              # Check package.json files for native dependencies
              if find "$dir/node_modules" -name "package.json" -type f -exec grep -l "react-native\|@react-native\|expo-\|@expo" {} \; | grep -q .; then
                return 0
              fi
              
              return 1
            }
            
            # Compare dependencies
            if [ -d "old_deps/node_modules" ] && [ -d "new_deps/node_modules" ]; then
              old_native=$(check_native_code "old_deps")
              new_native=$(check_native_code "new_deps")
              
              if [ "$old_native" != "$new_native" ] || check_native_code "new_deps"; then
                ios_changed=true
                android_changed=true
              fi
            fi
            
            # Cleanup
            rm -rf old_deps new_deps old_package.json new_package.json
          fi
          
          # Set outputs
          echo "ios_changes=$ios_changed" >> $GITHUB_OUTPUT
          echo "android_changes=$android_changed" >> $GITHUB_OUTPUT

  setup_and_lint:
    if: github.actor != 'roswaaltifbot' && !startsWith(github.event.pull_request.title, 'IGNORE_BUILD')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js and Cache
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install Dependencies
        run: |
          if [ ! -d "node_modules" ]; then
            echo "Cache not found, running npm ci."
            npm ci
          else
            echo "Cache restored, skipping npm ci."
          fi
        env:
          TIFSHARED_JS: true

      - name: Lint
        run: npm run staged-lint

  unit_tests:
    needs: setup_and_lint
    if: github.actor != 'roswaaltifbot' && !startsWith(github.event.pull_request.title, 'IGNORE_BUILD')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install Dependencies
        run: |
          if [ ! -d "node_modules" ]; then
            echo "Cache not found, running npm ci."
            npm ci
          else
            echo "Cache restored, skipping npm ci."
          fi
        env:
          TIFSHARED_JS: true

      - name: Setup Environment
        run: echo "API_URL=${{ secrets.API_ENDPOINT }}" >> .env

      - name: Run Tests
        run: npm run test:ci

  build:
    needs: unit_tests
    if: github.actor != 'roswaaltifbot' && !startsWith(github.event.pull_request.title, 'IGNORE_BUILD')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Bundle Project
        run: npx expo export --platform ios --platform android

  wait_for_review:
    needs: [check_platform_changes]
    if: |
      github.actor != 'roswaaltifbot' && 
      !startsWith(github.event.pull_request.title, 'IGNORE_BUILD') && 
      (needs.check_platform_changes.outputs.ios_changes == 'true' || needs.check_platform_changes.outputs.android_changes == 'true')
    runs-on: ubuntu-latest
    environment:
      name: eas-build
      url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - run: echo "Waiting for environment review"

  create_build_checkruns:
    needs: [build, check_platform_changes]
    if: |
      github.actor != 'roswaaltifbot' && 
      !startsWith(github.event.pull_request.title, 'IGNORE_BUILD') &&
      needs.check_platform_changes.outputs.ios_changes == 'false' &&
      needs.check_platform_changes.outputs.android_changes == 'false'
    runs-on: ubuntu-latest
    outputs:
      ios_checkrun_id: ${{ steps.ios-checkrun.outputs.checkrun_id }}
      android_checkrun_id: ${{ steps.android-checkrun.outputs.checkrun_id }}
    steps:
      - name: Create iOS Check Run
        id: ios-checkrun
        uses: actions/github-script@v6
        with:
          script: |
            const checkRun = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: process.env.IOS_CHECK_NAME,
              head_sha: context.payload.pull_request.head.sha,
              status: 'completed',
              started_at: new Date().toISOString(),
              completed_at: new Date().toISOString(),
              conclusion: 'success',
              output: {
                title: 'No iOS Changes Detected',
                summary: 'No native iOS changes were detected in this PR'
              }
            });
            core.setOutput('checkrun_id', checkRun.data.id);

      - name: Create Android Check Run
        id: android-checkrun
        uses: actions/github-script@v6
        with:
          script: |
            const checkRun = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: process.env.ANDROID_CHECK_NAME,
              head_sha: context.payload.pull_request.head.sha,
              status: 'completed',
              started_at: new Date().toISOString(),
              completed_at: new Date().toISOString(),
              conclusion: 'success',
              output: {
                title: 'No Android Changes Detected',
                summary: 'No native Android changes were detected in this PR'
              }
            });
            core.setOutput('checkrun_id', checkRun.data.id);

  eas_build:
    needs: [build, check_platform_changes, wait_for_review]
    if: |
      github.actor != 'roswaaltifbot' && 
      !startsWith(github.event.pull_request.title, 'IGNORE_BUILD') &&
      (needs.check_platform_changes.outputs.ios_changes == 'true' || needs.check_platform_changes.outputs.android_changes == 'true')
    name: Request EAS Builds
    runs-on: ubuntu-latest
    env:
      EXPO_PROJECT_ID: ${{ secrets.EXPO_PROJECT_ID }}
      EXPO_PROJECT_OWNER: ${{ secrets.EXPO_PROJECT_OWNER }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js and Cache
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Dependencies
        run: |
          if [ ! -d "node_modules" ]; then
            echo "Cache not found, running npm ci."
            npm ci
          else
            echo "Cache restored, skipping npm ci."
          fi

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_ACCESS_TOKEN }}

      - name: Setup Base Environment
        run: |
          {
            echo "GITHUB_SHA=${{ github.event.pull_request.head.sha }}"
            echo "GITHUB_BRANCH=${{ github.event.pull_request.head.ref }}"
            echo "GITHUB_REPOSITORY=${{ github.repository }}"
            echo "RUN_EAS_BUILD_HOOKS=1"
            echo "EXPO_PROJECT_ID=${{ secrets.EXPO_PROJECT_ID }}"
            echo "EXPO_PROJECT_OWNER=${{ secrets.EXPO_PROJECT_OWNER }}"
            echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}"
          } >> .env.infra

      - name: Request iOS Build
        if: needs.check_platform_changes.outputs.ios_changes == 'true'
        run: |
          {
            echo "CHECK_RUN_NAME=${{ env.IOS_CHECK_NAME }}"
            echo "PLATFORM=IOS"
            echo "CHECK_RUN_ID=${{ needs.create_build_checkruns.outputs.ios_checkrun_id }}"
          } >> .env.infra
          npm run eas_build_ci_ios
        env:
          EXPO_ACCESS_TOKEN: ${{ secrets.EXPO_ACCESS_TOKEN }}

      - name: Request Android Build
        if: needs.check_platform_changes.outputs.android_changes == 'true'
        run: |
          {
            echo "CHECK_RUN_NAME=${{ env.ANDROID_CHECK_NAME }}"
            echo "PLATFORM=ANDROID"
            echo "CHECK_RUN_ID=${{ needs.create_build_checkruns.outputs.android_checkrun_id }}"
          } >> .env.infra
          npm run eas_build_ci_android
        env:
          EXPO_ACCESS_TOKEN: ${{ secrets.EXPO_ACCESS_TOKEN }}