name: Attach PR to Trello Ticket

on:
  pull_request:
    types: [opened]
    branches:
      - development

jobs:
  check-existing-comment:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check-comment.outputs.skip }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for existing Trello link comment
        id: check-comment
        run: |
          COMMENTS_URL=${{ github.event.pull_request.comments_url }}
          COMMENT_FOUND=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $COMMENTS_URL | jq -r '.[] | select(.body | test("^Linked Ticket: https://trello.com/c/"))')
          if [[ -n "$COMMENT_FOUND" ]]; then
            echo "::set-output name=skip::true"
            echo "Existing Trello link found, skipping..."
          else
            echo "::set-output name=skip::false"
          fi

  link-ticket:
    needs: check-existing-comment
    if: needs.check-existing-comment.outputs.skip == 'false'
    runs-on: ubuntu-latest
    outputs:
      card_id: ${{ steps.extract-card-id.outputs.card_id }}  # Corrected: Ensure card_id is an output of the job
    steps:
      - name: Safe Handling of PR Body
        run: |
          ENCODED_BODY=$(echo "${{ github.event.pull_request.body }}" | base64 -w 0)
          echo "ENCODED_BODY=$ENCODED_BODY" >> $GITHUB_ENV

      - name: Extract Trello Card ID from Encoded Branch Name or PR Body
        id: extract-card-id  # Corrected: Added id to this step
        run: |
          PR_BODY=$(echo "$ENCODED_BODY" | base64 --decode)
          BRANCH_NAME="${{ github.head_ref }}"
          TRELLO_CARD_ID=$(echo "$BRANCH_NAME" | grep -oP '(?i:task)_\K[A-Za-z0-9]+' || echo "$PR_BODY" | grep -oP '(?i:task)_\K[A-Za-z0-9]+' || echo "")
          if [[ -z "$TRELLO_CARD_ID" ]]; then
            echo "No card ID found in branch name or PR body."
            exit 1
          else
            echo "Found Card ID: $TRELLO_CARD_ID"
            echo "::set-output name=card_id::$TRELLO_CARD_ID"
          fi

      - name: Link PR and Trello Ticket
        run: |
          TRELLO_CARD_ID="${{ needs.link-ticket.outputs.card_id }}"  # Corrected: Properly reference the output of the card_id step

          # Define Card URL
          TRELLO_CARD_URL="https://trello.com/c/$TRELLO_CARD_ID"

          # URL of the Pull Request
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_NAME="Pull Request #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"

          # Attach PR to Trello Card
          TRELLO_RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST "https://api.trello.com/1/cards/$TRELLO_CARD_ID/attachments" \
          -d "key=${TRELLO_API_KEY}" \
          -d "token=${TRELLO_API_TOKEN}" \
          -d "url=${PR_URL}" \
          -d "name=${PR_NAME}")
          echo "Trello API Response Code: $TRELLO_RESPONSE"
          echo "Trello API Response Body:"
          cat response.json

          if [[ "$TRELLO_RESPONSE" -ne 200 ]]; then
            echo "Failed to attach PR to card. Response code: $TRELLO_RESPONSE"
            cat response.json
            exit 1
          else
            echo "PR successfully attached to Trello card."
          
          # Comment on the GitHub PR with the card link
          COMMENT_BODY="Linked Ticket: $TRELLO_CARD_URL"
          curl -s -H "Authorization: token ${{ secrets.USER_GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d "{\"body\": \"$COMMENT_BODY\"}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
